### PR TITLE
ci: Update espressif-ide version to 2.5.0

### PR DESCRIPTION
**Pull request by kolipakakondal**

### CODE REVIEW

**Comment by kolipakakondal** [comment]
Hi @georgik Where can I pick the PR build so that I could verify Espressif-IDE with the offline installer with these changes?

**Comment by georgik** [comment]
@kolipakakondal The build is triggered by tag:
```
git tag espressif-ide-2.5.0
git push origin espressif-ide-2.5.0
```

Build is running, you can see it above this comment. Once completed it will be available in the release and also at dl.espressif.com

@alirana01 Is this installer for IDE still required? AFAIK new IDE contains the installer inside.

**Comment by kolipakakondal** [comment]
Hi @georgik Thanks for the details.

Espressif-IDE doesn't have an installer inside. We are recommending Espressif-IDE windows installer what you've built to our community and customers. There is no immediate plan also for this.

Ali is trying to build managing tools within the IDE, it's basically what we could do with idf_tools.py but natively using Java to have more control over the installation and driving end-to-end workflow from a single wizard.

@alirana01  Maybe you could give a short demo to @georgik to get feedback on what you are working on.

**Comment by georgik** [comment]
Test of installation on Offline machine passed. Merging. Thanks for the contribution.

**Pull request merged**
